//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Bekap_4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Запись визита.
    /// </summary>
    // *** Start programmer edit section *** (ЗаписьВизита CustomAttributes)

    // *** End programmer edit section *** (ЗаписьВизита CustomAttributes)
    [AutoAltered()]
    [Caption("Запись визита")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаписьВизитаE", new string[] {
            "Стоимость as \'Стоимость\'",
            "Комментарий as \'Комментарий\'",
            "Услуга as \'Услуга\'",
            "Услуга.Наименование as \'Наименование\'",
            "сотрудник as \'Сотрудник\'",
            "сотрудник.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Услуга.Наименование",
            "сотрудник.ФИО"})]
    [MasterViewDefineAttribute("ЗаписьВизитаE", "Услуга", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("ЗаписьВизитаE", "сотрудник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    public class ЗаписьВизита : ICSSoft.STORMNET.DataObject
    {
        
        private double fСтоимость;
        
        private string fКомментарий;
        
        private IIS.Bekap_4.Услуга fУслуга;
        
        private IIS.Bekap_4.сотрудник fсотрудник;
        
        private IIS.Bekap_4.Визит fВизит;
        
        // *** Start programmer edit section *** (ЗаписьВизита CustomMembers)

        // *** End programmer edit section *** (ЗаписьВизита CustomMembers)

        
        /// <summary>
        /// Комментарий.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьВизита.Комментарий CustomAttributes)

        // *** End programmer edit section *** (ЗаписьВизита.Комментарий CustomAttributes)
        [StrLen(255)]
        public virtual string Комментарий
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьВизита.Комментарий Get start)

                // *** End programmer edit section *** (ЗаписьВизита.Комментарий Get start)
                string result = this.fКомментарий;
                // *** Start programmer edit section *** (ЗаписьВизита.Комментарий Get end)

                // *** End programmer edit section *** (ЗаписьВизита.Комментарий Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьВизита.Комментарий Set start)

                // *** End programmer edit section *** (ЗаписьВизита.Комментарий Set start)
                this.fКомментарий = value;
                // *** Start programmer edit section *** (ЗаписьВизита.Комментарий Set end)

                // *** End programmer edit section *** (ЗаписьВизита.Комментарий Set end)
            }
        }
        
        /// <summary>
        /// Стоимость.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьВизита.Стоимость CustomAttributes)

        // *** End programmer edit section *** (ЗаписьВизита.Стоимость CustomAttributes)
        public virtual double Стоимость
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьВизита.Стоимость Get start)

                // *** End programmer edit section *** (ЗаписьВизита.Стоимость Get start)
                double result = this.fСтоимость;
                // *** Start programmer edit section *** (ЗаписьВизита.Стоимость Get end)

                // *** End programmer edit section *** (ЗаписьВизита.Стоимость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьВизита.Стоимость Set start)

                // *** End programmer edit section *** (ЗаписьВизита.Стоимость Set start)
                this.fСтоимость = value;
                // *** Start programmer edit section *** (ЗаписьВизита.Стоимость Set end)

                // *** End programmer edit section *** (ЗаписьВизита.Стоимость Set end)
            }
        }
        
        /// <summary>
        /// Запись визита.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьВизита.сотрудник CustomAttributes)

        // *** End programmer edit section *** (ЗаписьВизита.сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "сотрудник"})]
        [NotNull()]
        public virtual IIS.Bekap_4.сотрудник сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьВизита.сотрудник Get start)

                // *** End programmer edit section *** (ЗаписьВизита.сотрудник Get start)
                IIS.Bekap_4.сотрудник result = this.fсотрудник;
                // *** Start programmer edit section *** (ЗаписьВизита.сотрудник Get end)

                // *** End programmer edit section *** (ЗаписьВизита.сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьВизита.сотрудник Set start)

                // *** End programmer edit section *** (ЗаписьВизита.сотрудник Set start)
                this.fсотрудник = value;
                // *** Start programmer edit section *** (ЗаписьВизита.сотрудник Set end)

                // *** End programmer edit section *** (ЗаписьВизита.сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Запись визита.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьВизита.Услуга CustomAttributes)

        // *** End programmer edit section *** (ЗаписьВизита.Услуга CustomAttributes)
        [PropertyStorage(new string[] {
                "Услуга"})]
        [NotNull()]
        public virtual IIS.Bekap_4.Услуга Услуга
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьВизита.Услуга Get start)

                // *** End programmer edit section *** (ЗаписьВизита.Услуга Get start)
                IIS.Bekap_4.Услуга result = this.fУслуга;
                // *** Start programmer edit section *** (ЗаписьВизита.Услуга Get end)

                // *** End programmer edit section *** (ЗаписьВизита.Услуга Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьВизита.Услуга Set start)

                // *** End programmer edit section *** (ЗаписьВизита.Услуга Set start)
                this.fУслуга = value;
                // *** Start programmer edit section *** (ЗаписьВизита.Услуга Set end)

                // *** End programmer edit section *** (ЗаписьВизита.Услуга Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Bekap_4.Визит.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьВизита.Визит CustomAttributes)

        // *** End programmer edit section *** (ЗаписьВизита.Визит CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Визит"})]
        public virtual IIS.Bekap_4.Визит Визит
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьВизита.Визит Get start)

                // *** End programmer edit section *** (ЗаписьВизита.Визит Get start)
                IIS.Bekap_4.Визит result = this.fВизит;
                // *** Start programmer edit section *** (ЗаписьВизита.Визит Get end)

                // *** End programmer edit section *** (ЗаписьВизита.Визит Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьВизита.Визит Set start)

                // *** End programmer edit section *** (ЗаписьВизита.Визит Set start)
                this.fВизит = value;
                // *** Start programmer edit section *** (ЗаписьВизита.Визит Set end)

                // *** End programmer edit section *** (ЗаписьВизита.Визит Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаписьВизитаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаписьВизитаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаписьВизитаE", typeof(IIS.Bekap_4.ЗаписьВизита));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ЗаписьВизита.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfЗаписьВизита CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfЗаписьВизита CustomAttributes)
    public class DetailArrayOfЗаписьВизита : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Bekap_4.DetailArrayOfЗаписьВизита members)

        // *** End programmer edit section *** (IIS.Bekap_4.DetailArrayOfЗаписьВизита members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ЗаписьВизита by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ЗаписьВизита.
        /// </summary>
        public DetailArrayOfЗаписьВизита(IIS.Bekap_4.Визит fВизит) : 
                base(typeof(ЗаписьВизита), ((ICSSoft.STORMNET.DataObject)(fВизит)))
        {
        }
        
        public IIS.Bekap_4.ЗаписьВизита this[int index]
        {
            get
            {
                return ((IIS.Bekap_4.ЗаписьВизита)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Bekap_4.ЗаписьВизита dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
